### ISSUE TITLE
Unrecognized field "readRoles" (class org.dashjoin.model.Table), not marked as ignorable

### ISSUE THREAD

**Issue by uw4** [dashjoin/dashjoin-demo#2]
When browsing any of the RDF4J types, i.e.
#/table/rdf4j/http:%2F%2Fwww.semwebtech.org%2Fmondial%2F10%2Fmeta%23Water

ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://localhost:4200/rest/database/crud/rdf4j/http%3A%2F%2Fwww.semwebtech.org%2Fmondial%2F10%2Fmeta%23Water?offset=0&limit=100","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:4200/rest/database/crud/rdf4j/http%3A%2F%2Fwww.semwebtech.org%2Fmondial%2F10%2Fmeta%23Water?offset=0&limit=100: 400 Bad Request","error":"Unrecognized field &quot;readRoles&quot; (class org.dashjoin.model.Table), not marked as ignorable"}

**Comment by aeberhart** [comment]
caused by a version incompatibility between platform and rdf4j service
